---
name: go
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11.4

  test:
    name: test
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26"

      - name: Bring up background services
        run: make dev/up

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.14.8

      - name: Execute terraform apply
        run: cd testing/terraform/vault && terraform init && terraform apply -auto-approve

      - name: Get dependencies
        run: go mod download

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@cb990680d22124dd5927ab91fe977567f5826722 # v2.0.0
        with:
          gotestsum_version: 1.13.0

      - name: Run tests
        run: make go/testsum

      - name: Stop background services
        run: make dev/down
