---
name: lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
