---
name: test
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          clean: false

      - name: Bring up background services
        run: make dev/up

      - name: Wait for services
        run: sleep 5 && make dev/logs

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Execute terraform apply
        run: cd testing/terraform/vault && terraform init && terraform apply -auto-approve

      - name: Get dependencies
        run: go mod download

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: 1.7.0

      - name: Run tests
        run: make go/testsum

      - name: Stop background services
        run: make dev/down
